[CD] Add enflame-gcu cd workflow

diff --git a/.github/workflows/enflame-gcu400-delivery.yml b/.github/workflows/enflame-gcu400-delivery.yml
--- a/.github/workflows/enflame-gcu400-delivery.yml
+++ b/.github/workflows/enflame-gcu400-delivery.yml
@@ -57,7 +57,7 @@ jobs:
           fi
 
           rm -rf ./build ./*.egg-info
-          MAX_JOBS=32 python${PYTHON_VER} setup.py bdist_wheel -d ~/dist-flagtree
+          ## MAX_JOBS=32 python${PYTHON_VER} setup.py bdist_wheel -d ~/dist-flagtree
           env | grep -E '^(FLAGTREE_WHEEL_VERSION)=' >> $GITHUB_ENV || true
 
       - name: FlagTree upload whl on Enflame
@@ -84,4 +84,19 @@ jobs:
           git config user.name "flagtree-bot"
           git config user.email "flagtree_ai@163.com"
           git tag -a "${FLAGTREE_WHEEL_VERSION}" -m "pypi ${FLAGTREE_WHEEL_VERSION}"
-          git push origin ${FLAGTREE_WHEEL_VERSION}
+          MAX_RETRY=10
+          RETRY_INTERVAL=10
+          success=false
+          for i in $(seq 1 $MAX_RETRY); do
+            echo "Attempt ${i} / ${MAX_RETRY}: git push origin ${GIT_TAG}"
+            if git push origin "${FLAGTREE_WHEEL_VERSION}"; then
+              success=true
+              break
+            fi
+            echo "Push failed, retrying in ${RETRY_INTERVAL}s..."
+            sleep $RETRY_INTERVAL
+          done
+          if [ "$success" != "true" ]; then
+            echo "git push failed after $MAX_RETRY attempts"
+            exit 1
+          fi
